### ISSUE TITLE
As a router, I need to know contract versioning and have the ability to upgrade/reference versions before submitting bids

### ISSUE THREAD

**Issue by LayneHaber** [connext/nxtp#1226]
## Background

If we upgrade contracts, routers should be able to check onchain and not bid on transfers if the contract version changes.

### Linked Issues & Documentation

N/A

## Definition Of Done

Routers and sequencers should be able to reference contract version number onchain before supporting transfers

## Tasks

- [x] Add version to contracts
- [ ] Add checks on router
- [ ] Add checks on sequencer
