### ISSUE TITLE
As a user I should not get impacted by agents having stuck polling loops

### ISSUE THREAD

**Issue by alexwhte** [connext/nxtp#1236]
### Problem to solve

Ensures system will not get locked up by a stuck loop.

### Solution Options
Use PM2 restart strategy: https://pm2.keymetrics.io/docs/usage/restart-strategies/

### Acceptance Criteria 

- [ ] 

### Subtasks

- [x] https://github.com/connext/nxtp/issues/1220
- [ ] https://github.com/connext/nxtp/issues/1221
- [ ] https://github.com/connext/nxtp/issues/1222
- [ ] https://github.com/connext/nxtp/issues/1223

**Comment by alexwhte** [comment]
@alexwhte Split this out at top-level

**Comment by alexwhte** [comment]
Archiving as we split out subtasks into new Master issues for scoping
