### ISSUE TITLE
PromiseRouter should store hash

### ISSUE THREAD

**Issue by LayneHaber** [connext/nxtp#1256]
## Background

The `PromiseRouter` should be storing the hash of the message, not the message itself

### Linked Issues & Documentation

N/A

## Definition Of Done

Promise router only stores hashes, relayers submit full message.

## Tasks

- [ ] Store hash of message not `bytes`
- [ ] Update interface to accept message in `bytes`
- [ ] Fix existing tests
