### ISSUE TITLE
As a backend DB user, I would benefit from lower latency on my requests to the DB

### ISSUE THREAD

**Issue by preethamr** [connext/nxtp#1259]
## Background

The backend DB users could benefit from improvements, that reduce the query/request latency. Adding indices on search columns like `transfer.status` is likely to help.

## Definition Of Done

Schema is upgraded to have necessary indices.

## Tasks

- [ ] List all columns that are used in any `WHERE` clause in any SQL query to the DB
- [ ] Add DB indices to all of these columns
- [ ] Validate the schema changes
- [ ] Add DB migrations for the schema changes
