### ISSUE TITLE
As a user, I want to see Router TVL per chain

### ISSUE THREAD

**Issue by rhlsthrm** [connext/nxtp#1684]
**Problem**
We need to recreate the TVL graph from Connextscan for Amarok:

<img width="1071" alt="Screen Shot 2022-08-03 at 17 55 08" src="https://user-images.githubusercontent.com/11512787/182665654-12a9f923-d261-422b-84e2-1752cd862c12.png">

**Subtasks**

- [ ] UI integration
- [ ] SDK method to `getRouterTVL` #1685 
- [ ] Cartographer Postgrest endpoint to get total TVL #1686 

**Acceptance Criteria**

- [ ] Graph on Connextscan shows breakdown of Amarok router TVL

**Other**
We have 2 types of TVL, routers and StableSwap AMM. This is only for routers.
