### ISSUE TITLE
As a dev user, I need to have a working messaging layer

### ISSUE THREAD

**Issue by LayneHaber** [connext/nxtp#1808]
**Problem**
Need a working messaging layer.

**Ideas to solve this**
Use AMBs as a stop gap. `SpokeConnector` contracts will update a merkle tree containing all outbound messages. Periodically, relayers will call `send()` on these spokes, which will dispatch the merkle root to a `RootManager` on a hub network via the `HubConnector`. The `HubConnector` is a contract which processes and sends message to through an AMB to a spoke, but lives on the hub domain.

The `RootManager` maintains its own Merkle tree which contains the `outboundRoot` for all spokes. Relayers can call `propagate` which will send the `aggregateRoot` through the `HubConnector` to the associated `SpokeConnector`s. Once the `aggregateRoot` has arrived at the destination spoke, the message can be processed after proving inclusion of the `message` in the `outboundRoot` and the `outboundRoot` in the stored `aggregateRoot`. 

**Acceptance Criteria**

- [x]  #1922 
    - [x]  `RootManager.sol`
    - [x]  `SendOutboundRootResolver`
    - [x]  `MainnetSpokeConnector.sol`
    - [x]  `OptimismHubConnector.sol`
    - [x]  `OptimismSpokeConnector.sol`
    - [x]  `GnosisHubConnector.sol`
    - [x]  `GnosisSpokeConnector.sol`
    - [x]  `PolygonHubConnector.sol`
    - [x]  `PolygonSpokeConnector.sol`
- [x] Merkle proofs must be updated to include proving the `outboundRoot` exists in the `aggregateRoot` : https://github.com/connext/nxtp/issues/1729
    - [x]  Add `MerkleTree` reference to `RootManager` [onchain]
    - [x]  Enforce proofs on `SpokeConnector` [onchain]
- [ ]  #1923 
    - [ ]  Add infrastructure for proving some `outboundRoot` exists in the `aggregateRoot`
    - [ ]  Add infrastructure for proving some message hash exists in an `outboundRoot`
    - [ ]  Create gelato task that will process a message when ready
- [ ] #1924  
In some cases, there are special onchain transactions needed to process the messages coming from a spoke to mainnet. These transactions will have to be relayed to ensure the RootManager gets the proper outboundRoot to include in aggregateRoots. Currently, the chains that need this are: optimism, polygon, and arbitrum.
    - [ ]  Setup the relay for optimism (see above) [offchain]
    - [ ]  Setup the relay for arbitrum (see above) [offchain]
    - [ ]  Setup the relay for polygon [offchain]
- [x] #1925 
    - [x]  Create the `Merkle` contract that allows public reads, but restricted writes. Should have the ability for the owner to update the writing address
    - [x]  Update `SpokeConnector` to have a reference to a `Merkle` contract instead of inheriting it
    - [x]  Update the `RootManager` to have a reference to a `Merkle` contract (no inherits)
- [x] #1926 specifically, add delay and ability to pause / disconnect by a watcher), which currently exists on the `RootManager`
    - [x]  Add watcher whitelist and associated updating functions to `SpokeConnector`
    - [x]  Remove watcher whitelist and associated updating functions from `RootManager`
    - [x]  Add `delayBlocks` to `SpokeConnector`
    - [x]  Enforce `delayBlocks` has elapsed before processing messages from `aggregateRoot` on `SpokeConnector`
    - [x]  Add a way for the owner to set the aggregate root when contract is disconnected
    - [x]  Add ability to reenable contract to process from existing aggregate root
- [ ]  #1927 
- [ ]  #1905
    - [ ]  Create a `processFromRoot` function on the `ArbitrumHubConnector`
        - [ ]  Should provide the `nodeNum` of the node with the given `sendRoot`
        - [ ]  Fetch the node with the given block using `Rollup.getNode`
        - [ ]  Verify the `confirmHash` to ensure the `sendRoot` is okay
        - [ ]  Prove inclusion of the message within the `sendRoot`
        - [ ]  Pass the `outboundRoot` to the `RootManager`
    - [ ]  Create a relayer task to call the `processFromRoot` function
        - [ ]  Should use the `send()` transaction hash to grab the `sendRoot`, `blockHash`, and `nodeNum` associated with a given `outboundRoot`
        - [ ]  Use the arbitrum sdk to get the outbox proof
        - [ ]  Call `processFromRoot` via Gelato
- [ ] #1928  (see Interim Solution doc for more details)
  - [ ]  Create a `processFromRoot` function on the `OptimismHubConnector`
      - [ ]  Reads latest root from `StateCommitmentChain`
      - [ ]  Performs the logic with provided L2 proof outlined [[here](https://github.com/ethereum-optimism/optimism/blob/9973c1da3211e094a180a8a96ba9f8bb1ab1b389/packages/contracts/contracts/L1/messaging/L1CrossDomainMessenger.sol#L283-L288)](https://github.com/et[here](https://github.com/ethereum-optimism/optimism/blob/9973c1da3211e094a180a8a96ba9f8bb1ab1b389/packages/contracts/contracts/L1/messaging/L1CrossDomainMessenger.sol#L304-L305)um-optimism/optimism/blob/9973c1da3211e094a180a8a96ba9f8bb1ab1b389/packages/contracts/contracts/L1/messaging/L1CrossDomainMessenger.sol#L283-L288) while adjusting the delay found [here](https://github.com/ethereum-optimism/optimism/blob/9973c1da3211e094a180a8a96ba9f8bb1ab1b389/packages/contracts/contracts/L1/messaging/L1CrossDomainMessenger.sol#L304-L305)
      - [ ]  Once proven, updates the outbound root on the `RootManager`
- [ ]  #1929 
      - [ ]  Should use the `send()` transaction hash (hash that generated the L2 → L1 message) to grab the message associated with an `outboundRoot` from subgraph
      - [ ]  Should use optimism sdk to generate proof
      - [ ]  Should call `processFromRoot` via Gelato

**Other**
- [Task Masterlist](https://www.notion.so/connext/Task-Masterlist-2ef41facb2c749b38201e19ac8f05355)
- [Interim solution notes](https://www.notion.so/connext/Interim-AMB-Messaging-f4690a794a984ac78e2504af062c4fea)
- [Interim solution diagram](https://whimsical.com/interim-solution-2v7wsknYkjcTmA2teLtrKV)

**Comment by alexwhte** [comment]
Closing in favor of #1936 using Zenhub tooling
