### ISSUE TITLE
As a team, we need to migrate the Merkle tree tracking all outbound messages to a separate contract to allow for easier upgrades

### ISSUE THREAD

**Issue by alexwhte** [connext/nxtp#1925]
From epic #1808 
- [x]  Create the `Merkle` contract that allows public reads, but restricted writes. Should have the ability for the owner to update the writing address
- [x]  Update `SpokeConnector` to have a reference to a `Merkle` contract instead of inheriting it
- [x]  Update the `RootManager` to have a reference to a `Merkle` contract (no inherits)

**Comment by jakekidd** [comment]
Duplicate of #1729

**Comment by jakekidd** [comment]
transferring over the story points for this as well @alexwhte

**Comment by LayneHaber** [comment]
reopening, not duplicate tasking

**Comment by jakekidd** [comment]
This was completed as part of https://github.com/connext/nxtp/pull/1934
