### ISSUE TITLE
As a dev user, I want to reference an updated docs site

### ISSUE THREAD

**Issue by just-a-node** [connext/nxtp#2025]
## Problem

Docs site should have all our updated architecture notes pertaining to the new AMB system. Most of the content has already been produced by the team, this task is a matter of moving everything into the docs site.

## Proposed Solution
- [x] Update Core Concepts of docs site
- [ ] Clean up diagrams 

## Acceptance Criteria
_From an end tester and/or user perspective, the below criteria must be met to consider this done:_
- [x] I can read all about Connext's messaging architecture and 
- [x] All the agents at play in the system
