### ISSUE TITLE
As a team, we have critical security additions and process to launch

### ISSUE THREAD

**Issue by alexwhte** [connext/nxtp#2163]
## Background
Security is paramount. We need to ensure we are covering all the critical bases that would block a launch

## Definition Of Done
All of the below are met
- [ ] Spearbit audit is completed
- [ ] Post-spearbit P0s are implemented
- [ ] Liquidity caps and admin rules are set
- [ ] Team has completed firedrills
- [ ] We have a watcher for balance checking

## Tasks to file
- [ ] Liquidity caps and admin rules are set
- [x] Internal firedrills and processes completed
- [x] Watcher agent is created and balance checking

## Out of launch scope
- Watcher agent is hash checking
- #1990
- #1389

### Linked Issues & Documentation
[Security Requirements notion](https://www.notion.so/connext/Security-Requirements-218f692c9cf84e79931e871b2efc4b77)
