### ISSUE TITLE
As a router, I can provide liquidity and monitor effectively

### ISSUE THREAD

**Issue by alexwhte** [connext/nxtp#2166]
## Background
To launch we need to provide routers a positive experience. This includes being able to add liquidity, being clear on instructions, and setting expectations on what features will be available 

### Linked Issues & Documentation
- [Router liquidity instructions](https://www.notion.so/connext/Router-Liquidity-Instructions-ecd56581365f4488976ccf9780ab7f7c)
- [Liquidity needs analysis + top routers ](https://docs.google.com/spreadsheets/d/15EWs6RDaETOq2wNY3UIgih0FC407mLbkb_1NsvjJhmQ/edit#gid=0)

## Definition Of Done
- [ ] Routers can add liquidity on mainnet
- [ ] We ensure liquidity needs are met per the spreadsheet 
- [ ] Routers are aware ahead of time and communicated to throughout launch
- [ ] Routers have enough metrics but also know what metrics will be fast-follows 

## Tasks to file
- [ ] Router operators can easily spin up a router
- [ ] Task 2?

## Out of scope - **Check these please and confirm not needed**
- #1541
- #1333
- #2111
- #1960
- #1862
- #1543
- #1499
- #1096
- #1722
