### ISSUE TITLE
[contracts] Staging env

### ISSUE THREAD

**Issue by LayneHaber** [connext/nxtp#961]
# Problem
We need a staging env so we can deploy changes and test them before releasing to testnets. There are additional offchain and ops changes that will go into this, but this issue will only reflect the changes needed for the `contracts` package.

# Solution
We should have a `Staging` tag added to the abi that is stored when we use the `hardhat-deploy` tool. Each hardhat task should also have an optional `--env "staging"` param (default to normal if not supplied) that will allow the task to select the right abi/contract for the env. There may *also* be changes needed to the logic of the task between staging and prod, and these should be included as well.

It's important to note that only *some* contracts would require a `staging` option (i.e. no reason to have a staging `TestERC20`)

# Tasks
- [ ] Update `deploy` to deploy to staging or prod
- [ ] Update tasks to have an `env` flag
- [ ] Deploy staging contracts
